### ISSUE TITLE
Question about training with fewer GPUs

### ISSUE THREAD

**Issue by Scalsol** [Sense-X/TSD#4]
Thanks for sharing your great work! I have several questions:
1. It seems like that you implement your training on 16 GPUs. I want to ask whether training on 4 GPUs will degrade the performance? Have you carried experiments on 4 GPUs?
2. You mentioned in your paper that SyncBN is used but it seems like this is missed in your config files? But the performance reported in this repo seems similar with the results in your paper.

BTW, I suggest you to merge all your TSD configs into a single directory :)

**Comment by songguanglu** [comment]
HI，thanks for your advice and I will merge the TSD configs into a single directory in the next update.
1.  Fewer GPUs will not degrade the performance and you should modify the training parameters according to the Tips in the readme.
2. TSD is firstly implemented in our own framework with SyncBN and in mmdet, we reimplement it with the BN both in baseline and TSD (In order to be consistent with the other algorithms in mmdet). We find the influence of BN is not obvious.

**Comment by Scalsol** [comment]
I see. Thanks for your reply :)
